### ISSUE TITLE
Implementation of Score-CAM

### ISSUE THREAD

**Issue by haofanwang** [PaddlePaddle/InterpretDL#1]
Score-CAM is a new gradient-free variant of CAMs. Is there any interest to implement it in Paddle?

Paper: [Score-CAM](https://openaccess.thecvf.com/content_CVPRW_2020/papers/w1/Wang_Score-CAM_Score-Weighted_Visual_Explanations_for_Convolutional_Neural_Networks_CVPRW_2020_paper.pdf)
Pytorch Code:[Implementation](https://github.com/haofanwang/Score-CAM)

**Comment by holyseven** [comment]
It's a nice work ! We are planning to implement it next week.

**Comment by haofanwang** [comment]
Thanks, @holyseven.

By the way, I have sent an email to you about possible job positions in your team, may you take a look?

**Comment by holyseven** [comment]
@haofanwang We were working on the tutorials this week, and didn't make it ... That would be the best if you (the author of Score-CAM) could implement it.

**Comment by haofanwang** [comment]
@holyseven Sure. I can do it when I am available. I will PR later.

**Comment by holyseven** [comment]
@haofanwang We have done Score-CAM. Could you help us to check the implementation? Thanks!

**Comment by haofanwang** [comment]
@holyseven LGTM. Thanks for your implementation. Closed.
