### ISSUE TITLE
能否在推断模型上计算得到gradient？

### ISSUE THREAD

**Issue by youwei2567** [PaddlePaddle/InterpretDL#11]
现在的模型都是基于“”训练模型“上做的。
如果要考虑到部署的情况，能否在“推断模型”上，去得到输出层到最后一层conv层的gradient？

**Comment by holyseven** [comment]
Hi @youwei2567 ，

如果这里的『部署』，指的是`model.eval()`，那其实我们目前的实现是等价于『部署模型』的，实现方式如下：

```python
self.paddle_model.train()

for n, v in self.paddle_model.named_sublayers():
    if n == self._target_layer_name:
        v.register_forward_post_hook(hook)
    if "batchnorm" in v.__class__.__name__.lower():
        v._use_global_stats = True
    if "dropout" in v.__class__.__name__.lower():
        v.p = 0
    # Report issues or pull requests if more layers need to be added.
```

如果『部署』是指的其它情况，那就需要具体讨论了。

**Comment by youwei2567** [comment]
> Hi @youwei2567 ，
> 
> 如果这里的『部署』，指的是`model.eval()`，那其实我们目前的实现是等价于『部署模型』的，实现方式如下：
> 
> ```python
> self.paddle_model.train()
> 
> for n, v in self.paddle_model.named_sublayers():
>     if n == self._target_layer_name:
>         v.register_forward_post_hook(hook)
>     if "batchnorm" in v.__class__.__name__.lower():
>         v._use_global_stats = True
>     if "dropout" in v.__class__.__name__.lower():
>         v.p = 0
>     # Report issues or pull requests if more layers need to be added.
> ```
> 
> 如果『部署』是指的其它情况，那就需要具体讨论了。

“部署”，就是指将训练模型(*.pdparams)用接口paddle.jit.save_inference_model()转换成推断模型(*.pdiparams)后，用于c++推断

**Comment by holyseven** [comment]
抱歉，目前应该是不支持，我们这边需要做一下测试。确认一下，以下链接是否符合所需场景：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/load_cn.html#cn-api-paddle-jit-load

**Comment by youwei2567** [comment]
> 抱歉，目前应该是不支持，我们这边需要做一下测试。
> 
> 确认一下，以下链接是否符合所需场景：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/load_cn.html#cn-api-paddle-jit-load

这种方法load得到的是TranslatedLayer这个对象，调其父类Layer方法named_sublayers()，[n for n, v in translated_layers.named_sublayers()]得到的是空列表，不应该啊？？

**Comment by holyseven** [comment]
@youwei2567 
参考[该Issue](https://github.com/PaddlePaddle/Paddle/issues/33900#issuecomment-872144415)。

**Comment by holyseven** [comment]
Free to reopen the issue if there are more questions.
