### ISSUE TITLE
你好，我想杠一下

### ISSUE THREAD

**Issue by lmk123568** [PaddlePaddle/InterpretDL#17]
https://github.com/PaddlePaddle/InterpretDL/blob/1d27e39f4ffc9029003f4d3f81c20d0f8d85c65d/interpretdl/interpreter/gradient_cam.py#L105

eval之后是有梯度的，具体可见[PPMA](https://github.com/lmk123568/Paddle_Model_Analysis)
感谢你们项目，获取梯度参考了你们几行代码
paddle完善hook，可能会更舒服一点
纯属交流~如果我理解有错欢迎讨论哈

**Comment by holyseven** [comment]
谢谢！eval对某些层好像没有梯度，比如`dropout`，应该在之后的版本会完善。欢迎交流~

```python

from ppma import cam
import paddle
from paddle.vision.models import mobilenet_v2
import matplotlib.pyplot as plt

img_path = 'assets/catdog.png'                                      # 图片路径
model = paddle.vision.models.mobilenet_v2(pretrained=True)     # 模型定义
# target_layer = model.pool2d_avg                            # 提取模型某层的激活图
target_layer = model.features.__dict__['_sub_layers']['18']
cam_extractor = cam.GradCAMPlusPlus(model, target_layer)   # 支持 GradCAM、XGradCAM、GradCAM++

# 提取激活图
activation_map = cam_extractor(img_path, label=None)   
plt.imshow(activation_map)
plt.axis('off')
plt.show()

```

> ValueError: (InvalidArgument) GradOp is only callable when is_test is false
    [Hint: Expected ctx->Attrs().Get<bool>("is_test") == false, but received ctx->Attrs().Get<bool>("is_test"):1 != false:0.] (at > /paddle/paddle/fluid/operators/dropout_op.cc:122)

**Comment by lmk123568** [comment]
> 谢谢！eval对某些层好像没有梯度，比如`dropout`，应该在之后的版本会完善。欢迎交流~
> 
> ```python
> from ppma import cam
> import paddle
> from paddle.vision.models import mobilenet_v2
> import matplotlib.pyplot as plt
> 
> img_path = 'assets/catdog.png'                                      # 图片路径
> model = paddle.vision.models.mobilenet_v2(pretrained=True)     # 模型定义
> # target_layer = model.pool2d_avg                            # 提取模型某层的激活图
> target_layer = model.features.__dict__['_sub_layers']['18']
> cam_extractor = cam.GradCAMPlusPlus(model, target_layer)   # 支持 GradCAM、XGradCAM、GradCAM++
> 
> # 提取激活图
> activation_map = cam_extractor(img_path, label=None)   
> plt.imshow(activation_map)
> plt.axis('off')
> plt.show()
> ```
> 
> > ValueError: (InvalidArgument) GradOp is only callable when is_test is false
> > [Hint: Expected ctx->Attrs().Get("is_test") == false, but received ctx->Attrs().Get("is_test"):1 != false:0.] (at > /paddle/paddle/fluid/operators/dropout_op.cc:122)

感谢回复！我在研究一下

**Comment by holyseven** [comment]
下个版本（paddle2.2）应该就会支持所有层在eval下取得gradient。[cf.](https://github.com/PaddlePaddle/Paddle/issues/34293#issuecomment-889129205)

我们也在改进代码中，谢谢支持！

**Comment by holyseven** [comment]
Free to reopen the issue if there are more questions.
