### ISSUE TITLE
请问 这个工具支持带有gcb的resnet模型的feature map的可视化吗

### ISSUE THREAD

**Issue by IvyGongoogle** [PaddlePaddle/InterpretDL#2]
如题，期待回复。
谢谢

**Comment by Baidu-BDL** [comment]
请问gcb有相关文献可以发一个吗？

**Comment by holyseven** [comment]
请问gcb有相关文献可以发一个吗？

feature map的可视化是指的用哪种方式呢？我们目前支持相关的是grad-CAM和score-CAM。

只要是paddle实现的模型，都是可以用我们的工具做可视化分析和可解释性分析的。

**Comment by wanghao19970205** [comment]
请问只要是paddle实现的模型，普通DNN也能评估是吗？

**Comment by holyseven** [comment]
@wanghao19970205 是的。但可视化方面可能会不太一样，需要看输入是什么样的数据。
