### ISSUE TITLE
interpretdl-特征可视化

### ISSUE THREAD

**Issue by NICECPU** [PaddlePaddle/InterpretDL#23]
请问我使用https://blog.csdn.net/PaddlePaddle/article/details/114609592这里面的教程

visualize_grayscale(gradients[0]) #将结果转化为灰度图，
对于这一句代码 我并没有找到库或是源文件什么的
加入我想要把特征激活的图转换灰度的 需要怎么做呢（例如：把激活的地方就是白色 未激活的就是黑色）
十分感谢你们的回复！

**Comment by holyseven** [comment]
Hi @NICECPU ，

可视化的代码重构过，可参考[GradCAM的例子](https://github.com/PaddlePaddle/InterpretDL/blob/master/interpretdl/interpreter/gradient_cam.py#L95-L98)。

如果只是想用二值的可视化，可以直接用类似代码：

```python
explanation_mask = np.zeros(explanation.shape, np.uint8)
explanation_mask[explanation > threshold] = 1
```

**Comment by NICECPU** [comment]
@holyseven ，十分感谢你的回复，我参考了GradCAM的代码，得到下面的程序
`import numpy as np
import interpretdl as it
from matplotlib import pyplot as plt
from paddle.vision.models import resnet50
from PIL import Image
paddle_model = resnet50(pretrained=True)  #获得模型
sg = it.SmoothGradInterpreter(paddle_model, use_cuda=True)  #把模型加载到可解释性算法中，这里我们用的是SmoothGrad算法 
gradients = sg.interpret('鹿.jpg', visual=True, save_path=None)  #展示结果
explanation=gradients[0]
explanation=explanation.transpose(1,2,0)
image_2d = explanation[:,:,2] 
percentile=99
vmax = np.percentile(image_2d, percentile)
vmin = np.min(image_2d)
x = np.clip((image_2d - vmin) / (vmax - vmin), 0, 1) * 255
x = np.uint8(x)
plt.imshow(x,'gray')
plt.axis("off")
plt.show()`

**Comment by NICECPU** [comment]
@holyseven ，十分感谢你的回复，我参考了GradCAM的代码，得到下面的程序
'''python
import numpy as np
import interpretdl as it
from matplotlib import pyplot as plt
from paddle.vision.models import resnet50
from PIL import Image
paddle_model = resnet50(pretrained=True)  #获得模型
sg = it.SmoothGradInterpreter(paddle_model, use_cuda=True)  #把模型加载到可解释性算法中，这里我们用的是SmoothGrad算法 
gradients = sg.interpret('鹿.jpg', visual=True, save_path=None)  #展示结果
explanation=gradients[0]
explanation=explanation.transpose(1,2,0)
image_2d = explanation[:,:,2] 
percentile=99
vmax = np.percentile(image_2d, percentile)
vmin = np.min(image_2d)
x = np.clip((image_2d - vmin) / (vmax - vmin), 0, 1) * 255
x = np.uint8(x)
plt.imshow(x,'gray')
plt.axis("off")
plt.show()
'''

**Comment by holyseven** [comment]
改了一下后面的处理代码，利用阈值即可得到二值图：

```python
image_2d = np.abs(explanation).sum(2)

percentile=90
threshold = np.percentile(image_2d, percentile)

explanation_mask = np.zeros(image_2d.shape, np.uint8)
explanation_mask[image_2d > threshold] = 1

plt.imshow(explanation_mask, 'gray')
plt.axis("off")
plt.show()
```

**Comment by NICECPU** [comment]
@holyseven 谢谢，十分感谢！我发现问题的关键了！

**Comment by holyseven** [comment]
Free to reopen the issue for more questions.
