### ISSUE TITLE
NormLIMENLPInterpreter的interpret函数多次调用结果会有异常

### ISSUE THREAD

**Issue by zhangyimi** [PaddlePaddle/InterpretDL#27]
NormLIMENLPInterpreter的interpret函数会调用lime方法，并将结果根据一个临时索引dict_key保存在一个字典中，下次调用如果索引存在则不调用lime方法，直接取字典中索引对应的结果。
但是dict_key每次都是从0开始计数的，所以如果连续多次调用interpret且输入的data不同，就会返回错误的结果。
![abfcf46cad65db0b4a9fc4279993f42e](https://user-images.githubusercontent.com/20926735/160118685-1ee92d12-c9b5-45e9-8533-49b9af413f07.png)
![e9492608aa4b244747f2a2a82f426944](https://user-images.githubusercontent.com/20926735/160118694-581d06f2-062a-4ff7-9627-2fc173ee9203.png)

另外temp_data_file设置为None时可否不保存结果，现在每次调用都会生成一个结果文件感觉不太方便。

**Comment by holyseven** [comment]
相关问题已由以上commits解决，若有新的问题，随时讨论。

This issue is addressed by the two related commits. Free feel to reopen it if there are more concerns.
