### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by Hoozits728** [PaddlePaddle/InterpretDL#37]
Hi, my name is Matt Cremeens and am interested in using your work for a research project.

---

## 🐛 Bug

Error upon installation

### To Reproduce

1. Installed PaddlePaddle following these instructions: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/macos-pip.html
2. pip install interpretdl
3. Received error below

If you have a code sample, error messages, stack traces, please provide it here as well.

```python
Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.

```

## (optional) Enviroment

If you know well the environment of your machine, please put the information below:

macOS
python3.9

**Comment by holyseven** [comment]
Hi Matt,

If you are using M1, it seems that some libraries with arm has some compatibility issues, see [this](https://github.com/numpy/numpy/issues/17569) for example.

In case that you are using [conda](https://www.anaconda.com/), you can add `CONDA_SUBDIR=osx-64`, forcing the installation of intel packages. The following scripts work on M1 mac:

```bash
CONDA_SUBDIR=osx-64 conda create -n sandbox2 python=3.9
conda activate sandbox2 
conda env config vars set CONDA_SUBDIR=osx-64
python -m pip install paddlepaddle==2.3.1 -i https://mirror.baidu.com/pypi/simple
pip install interpretdl -i https://pypi.tuna.tsinghua.edu.cn/simple
```

If conda is not used, I didn't find easy solutions, except installing anaconda or [miniconda](https://docs.conda.io/en/latest/miniconda.html) simply, to handle your python environments.

See if this helps.

**Comment by Hoozits728** [comment]
I'm happy to report that your solution seems to have worked. I appreciate the fast response. Thanks so much.
