### ISSUE TITLE
你好，请问对一般离散特征的数值型数据，怎么使用该工具包呢

### ISSUE THREAD

**Issue by wanghao19970205** [PaddlePaddle/InterpretDL#4]
比如在推荐系统中，我们一般使用的数据很少是图片和text类型的，一般都是数值型连续或者离散特征的数据，对于这种普遍的应用场景，有没有打算支持呢？

**Comment by holyseven** [comment]
@wanghao19970205 你好，请问这个推荐系统的模型也是paddle的模型吗？如果是的话，SmoothGrad应该是支持的，不过需要模型可以求导；LIME理论上也是可以的，但需要额外操作。有简单的demo话，我们可以帮助测试。

**Comment by wanghao19970205** [comment]
对的，是paddle模型，打算调研厂内各种评估方法，目前使用最基本的https://github.com/PaddlePaddle/PaddleRec/tree/master/models/rank/dnn来对这个工具进行测试，请问你们能够看一下，提供一些指导嘛

**Comment by holyseven** [comment]
@wanghao19970205 我们这边开始测试这个模型了，但需要一些时间。欢迎厂内直接联系沟通~

**Comment by wanghao19970205** [comment]
好嘞~非常感谢
