### ISSUE TITLE
热力图

### ISSUE THREAD

**Issue by NwTbbetter** [PaddlePaddle/InterpretDL#41]
(optional) Briefly introduce yourself.

请问使用interpretDL绘制ppyoloe的热力图，如何加载模型？
如果在infer.py里这样写会报这样的错误
![image](https://user-images.githubusercontent.com/99952437/199042829-c50688e0-3382-4cdd-85ce-2fb35d98af1e.png)
![image](https://user-images.githubusercontent.com/99952437/199042921-aecf020b-0f14-4f33-8229-10111950d127.png)

**Comment by holyseven** [comment]
目标检测的热力图，目前只能参考GradCAM：https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCam_Object_Detection.ipynb。

**Comment by NwTbbetter** [comment]
> 目标检测的热力图，目前只能参考GradCAM：https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCam_Object_Detection.ipynb
> 
> 其它的算法目前只支持分类模型。

好嘞，那请问怎么在原图上绘制？这个链接是在预测框内绘制热力图

**Comment by holyseven** [comment]
嗯，是的。链接中的绘制是在框内进行绘制。

如果要在原图上直接绘制，那直接在`img`上进行绘制即可，修改以下代码：
```
overlay_vis = np.uint8(resized_exp_in_img * 0.4 + img * 0.6)
```
其中`resized_exp_in_img`需要把`resized_exp`放回原图的坐标下。

**Comment by NwTbbetter** [comment]
> 嗯，是的。链接中的绘制是在框内进行绘制。
> 
> 如果要在原图上直接绘制，那直接在`img`上进行绘制即可，修改以下代码：
> 
> ```
> overlay_vis = np.uint8(resized_exp_in_img * 0.4 + img * 0.6)
> ```
> 
> 其中`resized_exp_in_img`需要把`resized_exp`放回原图的坐标下。

怎么映射回原图啊...

**Comment by holyseven** [comment]
可能是这样，可以试试（不保证一定对...）

```python

resized_exp_in_img = np.zeros((img.shape[0], img.shape[1]))
resized_exp_in_img[int(tl_y*scaler):int(tl_y*scaler+height*scaler), int(tl_x*scaler):int(tl_x*scaler+width*scaler)] = resized_exp

```

**Comment by NwTbbetter** [comment]
> 可能是这样，可以试试（不保证一定对...）
> 
> ```python
> resized_exp_in_img = np.zeros((img.shape[0], img.shape[1]))
> resized_exp_in_img[int(tl_y*scaler):int(tl_y*scaler+height*scaler), int(tl_x*scaler):int(tl_x*scaler+width*scaler)] = resized_exp
> ```

不好意思，这个还是不行呀，因为感觉这个代码一开始就是只是把检测框的那个区域送入算了梯度。如果要整张图应该怎么做啊

**Comment by holyseven** [comment]
有两个方案：
- 计算backbone里某一层的features*对应的gradients。这样做resize后，直接得到的就是整张图的热力图。但是只能在backbone里的一层上进行，离最后一层较远，会导致gradcam的结果与任务相关性减弱。
- 按照这个[链接](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCam_Object_Detection.ipynb)里的计算框内的热力图，然后在整张图上显示热力图。这样除了框内有热力图，其它地方都是黑的。

之前说的那个映射，是基于第二个方案的。不知道是否和你想要的一致？
