### ISSUE TITLE
关于分割模型的可视化

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/InterpretDL#42]
请问目前有关于分割模型可视化的热力图方法吗，
我使用gradcam的教程在自己网络尝试，
显示我的维度不对，不知道该怎么处理。

**Comment by holyseven** [comment]
我们之后准备release分割的demo。目前的话，需要在开发模式下进行修改gradcam的源代码；使用smoothgrad或者intgrad也是一种选择。

**Comment by xiaodaomingye459** [comment]
大概多久更新呢，
我在使用intgrad时遇到如下问题：
![image](https://user-images.githubusercontent.com/83204995/200561853-e92ea573-e75a-4ef5-b67b-db33e0e7b129.png)

**Comment by holyseven** [comment]
暂时安排到下个月。

这个大概思路是在`InputGradientInterpreter`的基础上，定制化一个predict_fn，让它适合segmentation模型，`IntGradCVInterpreter`基本不用怎么改。当然，像`reshape`的问题还是需要修改一下，匹配segmentation的输出。

**Comment by holyseven** [comment]
分割模型GradCAm的解释： https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb
