### ISSUE TITLE
Infidelity metric not found, probably a new release needed

### ISSUE THREAD

**Issue by adubowski** [PaddlePaddle/InterpretDL#44]
## ❓ Questions and Help
Could you make a new release so that pip install includes newer features like the Infidelity metric? Other metrics are found without problems

**Comment by holyseven** [comment]
A new version of pip is released. 
Please note that the [official implementation](https://github.com/chihkuanyeh/saliency_evaluation) of `Infidelity` on images uses the stride of 1, while we use a large stride of 8 for reducing computations.
