### ISSUE TITLE
长宽不相等的图像怎么输入

### ISSUE THREAD

**Issue by 245680** [PaddlePaddle/InterpretDL#48]
interpret的resize_to参数只能填一个数,我的网络长和宽不相等怎么送进gradcam分析

**Comment by holyseven** [comment]
目前的解决方案是这样：
- 先处理好：image_path (str) -> input_data (numpy.ndarray, float) （即normalized之后的数据，值域大致在-1到-1左右）；
- 然后直接输入给`interpret`的`inputs`，这样resize_to和crop_to不会对数据产生影响。

**Comment by 245680** [comment]
> 目前的解决方案是这样：
> 
> * 先处理好：image_path (str) -> input_data (numpy.ndarray, float) （即normalized之后的数据，值域大致在-1到-1左右）；
> * 然后直接输入给`interpret`的`inputs`，这样resize_to和crop_to不会对数据产生影响。

我的数据集和网络的输入是68*120,由1080p的图片降采样得到.  224*224图像送进去在全连接层会报错.
如果为了解释我的网络的原理把我的网络和数据集都改了,训练一个新的网络,这样就划不来了

**Comment by holyseven** [comment]
不用重训网络。`interpret`的输入可以是str 也可以是`numpy.ndarray`

**Comment by 245680** [comment]
我的网络是回归而不是分类,是不是要大面积改interpretdl源文件
现在是报这个错
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_8104/1753307740.py in <module>
      5 tmp=I1
      6 algo = it.GradCAMInterpreter(sunet, device='cpu')
----> 7 explanation = algo.interpret(tmp, '1', label=0)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/interpretdl/interpreter/gradient_cam.py in interpret(self, inputs, target_layer_name, label, resize_to, crop_to, visual, save_path)
     96         g = gradients
     97 
---> 98         print(f.shape, g.shape)  # [bsz, channels, w, h]
     99 
    100         # the core algorithm

AttributeError: 'NoneType' object has no attribute 'shape'`

**Comment by holyseven** [comment]
有几点需要注意的：

- 首先确定梯度是否能够计算，Paddle之前有几个版本在`eval`下是不支持梯度回传的。目前的报错可能是梯度没有回传；也有可能是计算梯度的方式是依照分类loss算的，计算上和回归有区别，导致没有梯度。需要确认一下。
- 不需要大面积修改源文件，但是的确需要修改一部分。[这几行](https://github.com/PaddlePaddle/InterpretDL/blob/master/interpretdl/interpreter/gradient_cam.py#L141-L146) 默认是分类的loss，需要改成回归loss的计算方式。
- gradcam在回归任务下效果无法保证。
- 可能还需要调整`target_layer_name`，一般是最后一个卷积层。
