### ISSUE TITLE
分割可视化

### ISSUE THREAD

**Issue by m828** [PaddlePaddle/InterpretDL#53]
我用给的示例代码运行分割模型
尝试了ppliteseg官方代码和权重，以及自己训练的权重，可视化的图形如下，是什么原因呢？
![image](https://user-images.githubusercontent.com/45037914/220294880-358235de-a473-406e-ad59-b6c3bf537dac.png)

**Comment by holyseven** [comment]
https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/InputGrad_Segmentation.ipynb

可以测试一下模型本身的预测结果是否正确，是否能正常可视化

**Comment by m828** [comment]
> https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/InputGrad_Segmentation.ipynb
> 
> 可以测试一下模型本身的预测结果是否正确，是否能正常可视化

不行哎
![image](https://user-images.githubusercontent.com/45037914/220331996-7cd65063-b1f3-4e8f-ac04-cb64f594bc0e.png)

**Comment by holyseven** [comment]
- 看看模型的weights是否成功load？
- 模型的输入是否正确？
- 看看其它的步骤是否正确？

**Comment by m828** [comment]
> * 看看模型的weights是否成功load？
> * 模型的输入是否正确？
> * 看看其它的步骤是否正确？

试了好几次，下载文件，cd InterpretDL && pip install -e .，也没报错，就是最开始路径问题，无法直接from paddleseg.models，只有这里修改了
![image](https://user-images.githubusercontent.com/45037914/220498347-213d68e5-1cf7-49fe-a591-87b5091c2dc5.png)
，其他地方都没有动

**Comment by m828** [comment]
仍然是这样
![image](https://user-images.githubusercontent.com/45037914/220498528-19041eda-bf45-4a16-8af6-253455b068d9.png)

**Comment by holyseven** [comment]
看看原始图片可以正常显示吗？

![image](https://user-images.githubusercontent.com/13829174/220502976-52be3d22-9833-4704-a84e-32cb19d7f553.png)

看目前的例子，好像paddleseg的预测都不正常

**Comment by m828** [comment]
> 看看原始图片可以正常显示吗？
> 
> ![image](https://user-images.githubusercontent.com/13829174/220502976-52be3d22-9833-4704-a84e-32cb19d7f553.png)
> 
> 看目前的例子，好像paddleseg的预测都不正常

图片可以正常显示，您那边的示例可以正常可视化吗

**Comment by holyseven** [comment]
![image](https://user-images.githubusercontent.com/13829174/220509761-3b40410e-064b-4da6-b2f3-06fb86603f8f.png)

![image](https://user-images.githubusercontent.com/13829174/220509821-e42b4e12-1151-489d-9e58-3845bd1103d0.png)

都是正常的。。

**Comment by m828** [comment]
> 

这。。请问paddleseg文件夹是和InterpretDL文件夹同级？我是将InterpretDL放入了paddleseg中

**Comment by holyseven** [comment]
- paddleseg我是用`pip install paddleseg`直接安装的。
- InterpretDL是`cd InterpretDL && pip install -e .` 安装的目前最新版本。
- Paddle我用的2.3.2

**Comment by m828** [comment]
> * `pip install -e .`

我又重新试了一次，可以了，非常感谢，还有一个问题，同样的主干网络，我只是修改了解码器，能达到和ppliteseg同样的精度，做推理效果也很好，但是可视化却有问题
ppliteseg：
![frankfurt_000001_011835_leftImg8bit](https://user-images.githubusercontent.com/45037914/220606514-c8e760c6-3f3b-4868-8a4d-13d0d0657a61.png)

![image](https://user-images.githubusercontent.com/45037914/220606134-fae3575c-d44c-4e37-8f4e-37d05ae96f70.png)
我的：
![frankfurt_000001_011835_leftImg8bit](https://user-images.githubusercontent.com/45037914/220606520-aab42f9c-d047-44ef-9c8d-71e6b1835688.png)

![image](https://user-images.githubusercontent.com/45037914/220606260-762a33db-199a-40e4-a40e-cf390638088b.png)
针对person的可视化，我的感觉什么都没捕获到

**Comment by holyseven** [comment]
模型结构和输出有变化吗？

**Comment by m828** [comment]
> 模型结构和输出有变化吗？


结构是有变化，
![image](https://user-images.githubusercontent.com/45037914/220795898-167040a5-861c-49d7-9192-e0706605c495.png)
![image](https://user-images.githubusercontent.com/45037914/220795897-794fd469-8fa2-49d5-ad57-dca5870108a0.png)
最后的输出，不都是通过seg_heads把通道转为与类别相同的通道数量了

**Comment by m828** [comment]
还是说中间有代码不支持可视化吗

**Comment by holyseven** [comment]
可回传梯度应该就没问题。

确认一下可视化的那个tensor是一个channel吗？是否进行了`np.abs(avg_gradients[i]).sum(0)`，类似这样的操作
![image](https://user-images.githubusercontent.com/13829174/220799470-fa545959-5a59-42c3-a549-5f4bff8fd0f7.png)

**Comment by m828** [comment]
> `np.abs(avg_gradients[i]).sum(0)`，

![image](https://user-images.githubusercontent.com/45037914/220800632-3e76ddbb-8e93-4ecb-bea1-7a260495338b.png)
是的

**Comment by holyseven** [comment]
暂时没有什么想法，试试其它像素点的解释结果，也是没什么东西吗？

**Comment by m828** [comment]
> 它像素点的

是的，就是一个模糊的轮廓，但我发现一个warning，不知道是否是这个原因
![Uploading image.png…]()

**Comment by holyseven** [comment]
这个截图似乎没有上传成功，我这边看不到

**Comment by m828** [comment]
> 这个截图似乎没有上传成功，我这边看不到

![image](https://user-images.githubusercontent.com/45037914/222019928-070c2d01-b40e-4196-803e-5d76ed4b725d.png)

**Comment by holyseven** [comment]
这个感觉不是大问题，我这边也有，但也还是正常的

**Comment by holyseven** [comment]
@m828 
之前的实现有个bug，看一下这一行axis应该是1而不是-1。这里对demo里的图片影响不大，但我看你用的cityscapes的图片，其宽为2048，可能对你的任务影响较大。
![image](https://user-images.githubusercontent.com/13829174/224652556-a094c216-6c46-427b-8a51-c57237d4aac6.png)

**Comment by m828** [comment]
> 

感谢，之前的问题解决了，是用默认的代码，权重没有加载完全，utils.utils.load_entire_model(m, trained_model_path)，加载下就可以了。现在还有一个问题，SmoothGrad可视化是针对类别的吧？我的目的是分析一类，比如person这一类的变化，应该怎么修改？
![image](https://user-images.githubusercontent.com/45037914/224706533-a6094e4d-3213-4138-b362-394c27cab855.png)

**Comment by m828** [comment]
> n是person那类的in

感谢！
