### ISSUE TITLE
Grad-CAM可视化分割模型

### ISSUE THREAD

**Issue by FelixYHH** [PaddlePaddle/InterpretDL#55]
(optional) Briefly introduce yourself.

---请问有Grad-CAM可视化分割模型的时间安排吗？

**Comment by holyseven** [comment]
Done!  See https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb

**Comment by FelixYHH** [comment]
> Done! See https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb

Thanks for the nice job!

**Comment by zcswdt** [comment]
> 完成！请参考https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb

import interpretdl as it
gradcam = GradCAMSegInterpreter(m, 'gpu:0')

pixels = [(400, 200)]
# good layers for deeplabv3p: backbone.bb_3_2.relu, head.aspp, head.decoder.conv
exp = gradcam.interpret(img_path, pixels, target_layer_name='backbone.bb_3_2.relu', resize_to=512, crop_to=512)请问一下在分割任务中的pixels = [(400, 200)]代表是什么意思呢？如果我换了图像这个参数怎么改呢？

**Comment by holyseven** [comment]
在 `interpret` 方法中，`pixels` 参数表示要聚合进行梯度计算的像素坐标。具体来说，它是一个包含多个像素点坐标的列表，每个像素点以 `(i, j)` 的形式表示，其中 `i` 表示像素的纵坐标（h 轴），`j` 表示像素的横坐标（w 轴）。这些像素点用来指示在输入图片中计算 GradCAM 时，在哪些位置聚合并计算梯度，最终用于生成热力图。

在 `predict_fn` 函数中，这些像素点被用于构建一个掩码 `mask`，这个掩码用于选择特定的像素来计算 logit 或者概率，并在这些像素点上进行聚合。这些像素的选择可以帮助我们更有针对性地对某些特定区域进行解释，而不是对整个图片进行解释。 

举个例子，如果你有一张图片，并且你只想对其中的某个感兴趣的区域进行解释，你可以通过提供对应的 `pixels` 参数来指定这个区域，然后 GradCAM 的结果会集中解释这些像素相关的内容。

**Comment by zcswdt** [comment]
> 在 `interpret` 方法中，`pixels` 参数表示要聚合进行梯度计算的像素坐标。具体来说，它是一个包含多个像素点坐标的列表，每个像素点以 `(i, j)` 的形式表示，其中 `i` 表示像素的纵坐标（h 轴），`j` 表示像素的横坐标（w 轴）。这些像素点用来指示在输入图片中计算 GradCAM 时，在哪些位置聚合并计算梯度，最终用于生成热力图。
> 
> 在 `predict_fn` 函数中，这些像素点被用于构建一个掩码 `mask`，这个掩码用于选择特定的像素来计算 logit 或者概率，并在这些像素点上进行聚合。这些像素的选择可以帮助我们更有针对性地对某些特定区域进行解释，而不是对整个图片进行解释。
> 
> 举个例子，如果你有一张图片，并且你只想对其中的某个感兴趣的区域进行解释，你可以通过提供对应的 `pixels` 参数来指定这个区域，然后 GradCAM 的结果会集中解释这些像素相关的内容。

非常感谢您的回复，但是我还是不知道该如何更换。我现在使用paddleseg分割模型来对图片进行1个类别的分割，然后模型输出 的是一个不是一个像素,如何修改呢？比如paddleseg网络模型输出如下：https://github.com/PaddlePaddle/PaddleSeg/blob/4b37151b0f4244bfb0b73609f9a8d67b33b7a7c0/paddleseg/core/infer.py#L165

**Comment by holyseven** [comment]
那个jupyter里，选取的pixels是猫的位置，目的是想看对于这些pixels，模型进行判断的理由是什么，即输入的图片中哪些地方比较重要

**Comment by zcswdt** [comment]
> 那个jupyter里，选取的pixels是猫的位置，目的是想看对于这些pixels，模型进行判断的理由是什么，即输入的图片中哪些地方比较重要

谢谢回复，那我如果是分割网络的输出呢？比如我想分割出来图片中的猫的位置，然后使用grad-cam可视化出来，怎么来调整这个参数呢？

**Comment by holyseven** [comment]
没太懂，pixels就是分割网络的输出。

**Comment by zcswdt** [comment]
> 然后 GradCAM 的结果会集中解释这些像素相关的内容

非常抱歉，我没解释清楚。举个例子，比如说我使用paddleseg网络输出的pred是480*480大小，其中像素点为0的地方是背景，为1的地方是猫的区域，然后是不是我可以这样理解，这个为1的区域就是这个pixels？然后我只需要将这个区域的替换成pixels就行了？就可以实现GradCAM 的效果了？

**Comment by holyseven** [comment]
如果按照目前的实现方式来说的话，
> 这个为1的区域就是这个pixels

是可以把为1的区域当做一个list当做pixels这个参数输入进去，实现图像分割的gradcam的效果。

不过需要提醒的是，这个gradcam的实现，没有经过严格的分析，只是一种可能的实现方式。

**Comment by zcswdt** [comment]
> 如果按照目前的实现方式来说的话，
> 
> > 这个为1的区域就是这个pixels
> 
> 是可以把为1的区域当做一个list当做pixels这个参数输入进去，实现图像分割的gradcam的效果。
> 
> 不过需要提醒的是，这个gradcam的实现，没有经过严格的分析，只是一种可能的实现方式。

阿？那怎么办？有没有更好的方法呢？谢谢回复！

**Comment by zcswdt** [comment]
> > 如果按照目前的实现方式来说的话，
> > > 这个1的区域就是这个像素
> > 
> > 
> > 是可以把为1的区域当做一个列表当做像素这个参数输入进去，实现图像分割的gradcam的效果。
> > 只是需要提醒的是，这个gradcam的实现，并没有经过严格的分析，一种可能的实现方式。
> 
> 阿？那怎么办？有没有更好的方法呢？谢谢回复！

gradcam = GradCAMSegInterpreter(m, 'gpu:0')

您好，我使用这个例子代码，生成图片是这种，和样例不一样，可以帮忙分析一下么？
pixels = [(400, 200)]
# good layers for deeplabv3p: backbone.bb_3_2.relu, head.aspp, head.decoder.conv
exp = gradcam.interpret(img_path, pixels, target_layer_name='backbone.bb_3_2.relu', resize_to=512, crop_to=512)
![image](https://github.com/user-attachments/assets/a1b5fc4a-b892-41d9-8679-b46ba0d77320)

**Comment by zcswdt** [comment]
您好，我使用这个例子代码，生成图片是这种，和样例不一样，可以帮忙分析一下么？
![image](https://github.com/user-attachments/assets/e13c13aa-6bc3-4e58-8efc-97356e742912)

![image](https://github.com/user-attachments/assets/67f683b5-4fa4-44c5-88dd-fffc0a955e76)

**Comment by holyseven** [comment]
可以尝试以下分析方法：
- 检测代码和模型，确认没有误操作
- 尝试复现 https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb，确认输出与demo一致
- 查看模型的分割结果，是否符合预期

**Comment by zcswdt** [comment]
> 可以尝试以下分析方法：
> 
> * 检测代码和模型，确认没有误操作
> * 尝试复现 [https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb，确认输出与demo一致](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb%EF%BC%8C%E7%A1%AE%E8%AE%A4%E8%BE%93%E5%87%BA%E4%B8%8Edemo%E4%B8%80%E8%87%B4)
> * 查看模型的分割结果，是否符合预期

我就是使用的这个，但是还是不行啊，可以帮忙调试一下么？

**Comment by zcswdt** [comment]
> 可以尝试以下分析方法：
> 
> * 检测代码和模型，确认没有误操作
> * 尝试复现 [https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb，确认输出与demo一致](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb%EF%BC%8C%E7%A1%AE%E8%AE%A4%E8%BE%93%E5%87%BA%E4%B8%8Edemo%E4%B8%80%E8%87%B4)
> * 查看模型的分割结果，是否符合预期

我使用例子代码，生成的热力图在狗上面，请问这个pixels = [(400, 200)]中的400是X轴还是Y轴呢？
![image](https://github.com/user-attachments/assets/a2bde6bd-4555-49df-809c-dc24e187f985)

**Comment by holyseven** [comment]
可以完整跑一下这个例子吗：

https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb

确认以下两点：

1. 这个分割的概率图是一致的：

![image](https://github.com/user-attachments/assets/77020d2d-a90c-4e37-9789-5d9ae786216a)

2. GradCAMSegInterpreter 这个代码没有改过

> 请问这个pixels = [(400, 200)]中的400是X轴还是Y轴呢？

400是y轴，200是x轴。所以 (400, 200) 是落在猫身上的。

我重新跑了一遍，和demo是一致的。

**Comment by zcswdt** [comment]
> 可以完整跑一下这个例子吗：
> 
> https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb
> 
> 确认以下两点：
> 
> 1. 这个分割的概率图是一致的：
> 
> ![image](https://private-user-images.githubusercontent.com/13829174/370960847-77020d2d-a90c-4e37-9789-5d9ae786216a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMTg3MDgsIm5iZiI6MTcyNzMxODQwOCwicGF0aCI6Ii8xMzgyOTE3NC8zNzA5NjA4NDctNzcwMjBkMmQtYTkwYy00ZTM3LTk3ODktNWQ5YWU3ODYyMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDAyNDAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNTljNDA2Zjg4ZDZhOGE1MDk3YTk4OTg3MmFmMGE1NDg5NDAyNzI3OTE3ODEzZmJkNmUyODExMzlmZTcwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s7CReAR2Ke7L3mwec5aX6ZXyGOz2qey5a2decfYk40k)
> 
> 2. GradCAMSegInterpreter 这个代码没有改过
> 
> > 请问这个pixels = [(400, 200)]中的400是X轴还是Y轴呢？
> 
> 400是y轴，200是x轴。所以 (400, 200) 是落在猫身上的。
> 
> 我重新跑了一遍，和demo是一致的。

1.我没改过代码，我完全复制的GradCAM_Segmentation.ipynb中的代码到我的pycharm中，运行分割图输出如下：
![image](https://github.com/user-attachments/assets/f940e3e9-3e91-46bf-87e5-13ea063f9a2b)

2.当我注释掉分割的那部分代码，使用gradcam来测试生成图如下：
![image](https://github.com/user-attachments/assets/8a84f9ff-6a1a-489c-b48a-85607ad46cf0)
3.我的paddle版本如下：
![image](https://github.com/user-attachments/assets/6796803f-3677-4f3a-8a2e-cef3e6645946)

**Comment by holyseven** [comment]
看起来分割的结果是一致的。我这边paddle版本2.5.2，不然你也试试？我这边环境不太好换。但不过感觉应该不会是版本差异带来的。

再试试不同的pixels的结果呢？

![image](https://github.com/user-attachments/assets/4c2a8190-d165-4024-9430-744c3c2748e4)
![image](https://github.com/user-attachments/assets/5ce315a1-fcfc-43b9-a867-729e7fd86dad)
![image](https://github.com/user-attachments/assets/69070364-0d05-4e83-95c6-133b5ac64a94)

其它暂时没有想到的潜在问题

**Comment by zcswdt** [comment]
> 看起来分割的结果是一致的。我这边paddle版本2.5.2，不然你也试试？我这边环境不太好换。但不过感觉应该不会是版本差异带来的。
> 
> 再试试不同的pixels的结果呢？

你的复现结果和我的大概一样，但是没有落到猫上面的热力图，所以这是什么原因导致的呢？
![image](https://github.com/user-attachments/assets/3213cbbc-a0e7-4f42-b32c-b68ddcc4f9d0)
![image](https://github.com/user-attachments/assets/5c32214c-e120-4aaf-9ac0-e62d2f82312b)
![image](https://github.com/user-attachments/assets/0356afab-497c-4b2f-988a-e1777883aa29)

**Comment by holyseven** [comment]
换几个在 (400, 200) 附近的pixels试试呢？

**Comment by zcswdt** [comment]
> 换几个在 (400, 200) 附近的pixels试试呢？

试过了，会落在猫上，但是不如你demo里面展示的那样，是不是代码哪里有问题？

**Comment by holyseven** [comment]
代码不是一样的嘛。。。

感觉大部分区域上是一致的，看看图片有区别吗？

**Comment by zcswdt** [comment]
> 换几个在 (400, 200) 附近的pixels试试呢？

换了几个点，这个热力图生成的也不是很好，pixels不是（y,x）
![image](https://github.com/user-attachments/assets/9e20d3bc-f46c-46f8-b029-0dfc85e3dd1f)
![image](https://github.com/user-attachments/assets/7e9351be-25ad-4ba2-803a-44d710b67828)
![image](https://github.com/user-attachments/assets/47fb63e1-a9a2-48d0-a1fa-38497f1cad48)
![image](https://github.com/user-attachments/assets/bfbd9567-0a79-460d-9e35-cf03afc30111)

**Comment by zcswdt** [comment]
> > 换几个在 (400, 200) 附近的pixels试试呢？
> 
> 换了几个点，这个热力图生成的也不是很好，pixels不是（y,x）我现在不知道怎么用了这个代码
 ![image](https://private-user-images.githubusercontent.com/43515926/371059080-9e20d3bc-f46c-46f8-b029-0dfc85e3dd1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTgxMDksIm5iZiI6MTcyNzM5NzgwOSwicGF0aCI6Ii80MzUxNTkyNi8zNzEwNTkwODAtOWUyMGQzYmMtZjQ2Yy00NmY4LWIwMjktMGRmYzg1ZTNkZDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzQzNmNiOTMwOTNhYTY1OGZjMjI1ZDJjN2NlNmNhMjhjMzc1MTMwNThjYmFkMmMyYTM1MTdlZmU4NTE1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.E3plzHJSSKXI5eHmxO0XL8ZEhx0RDn6FxPOecxfxnKM) ![image](https://private-user-images.githubusercontent.com/43515926/371059223-7e9351be-25ad-4ba2-803a-44d710b67828.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTgxMDksIm5iZiI6MTcyNzM5NzgwOSwicGF0aCI6Ii80MzUxNTkyNi8zNzEwNTkyMjMtN2U5MzUxYmUtMjVhZC00YmEyLTgwM2EtNDRkNzEwYjY3ODI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZWYwMDZkNTBjZDJjOTM2NGQ2Mjk5ZjE2ODAzZDljY2IxN2QwNjdlZmJmNDMyYjdjNjcyYmFjMWNkYTU0YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ycVGOVgl8fRTbVbSif7QYhHMaBg17OmJDX1GuYmcNTg) ![image](https://private-user-images.githubusercontent.com/43515926/371059695-47fb63e1-a9a2-48d0-a1fa-38497f1cad48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTgxMDksIm5iZiI6MTcyNzM5NzgwOSwicGF0aCI6Ii80MzUxNTkyNi8zNzEwNTk2OTUtNDdmYjYzZTEtYTlhMi00OGQwLWExZmEtMzg0OTdmMWNhZDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YzY3ZThjNjUxYjQyOTkwNTNkMmJmN2YzYTQwZmIxYzVjYjIyNzhmZDM0NDllNzJjZTAwNzhiMDYyYzE3NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HirvBLah8ROisLNPqKSUTzfdy6FFxDspmtTBhm0mGzw) ![image](https://private-user-images.githubusercontent.com/43515926/371060003-bfbd9567-0a79-460d-9e35-cf03afc30111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczOTgxMDksIm5iZiI6MTcyNzM5NzgwOSwicGF0aCI6Ii80MzUxNTkyNi8zNzEwNjAwMDMtYmZiZDk1NjctMGE3OS00NjBkLTllMzUtY2YwM2FmYzMwMTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZWJmNTZjOTQ0NzRhZDg2MTAwMTQzM2M1YzgwNTc3OWI4OTA2NTg3MzYzMjNlZDI2Y2UwOGIzZDkxNjRkZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.saWUVL8oAiY3VPYvfdIGXvm8tl9qCsWWMCqNkjB5TFQ)

**Comment by holyseven** [comment]
> 感觉大部分区域上是一致的，看看图片有区别吗？

我的意思是` img_path = 'assets/catdog.png'` 这张图片，和你用的图片是一样的吗？我看你重新保存成了jpg，可能图片像素信息不一样了。不过pixels的确是 (y, x)。

**Comment by zcswdt** [comment]
> > 感觉大部分区域都是一致的，看看图片有区别吗？
> 
> 我的意思是` img_path = 'assets/catdog.png'`这张图片，和你用的图片一样的吗？我看你重新保存成了jpg，可能图片像素信息不一样了。不过像素并不是(y,x)。

这个已经解决了，确实由于jpg的原因才和例子不一样的，谢谢！然后我将这个代码集成在paddleseg中，出现如下报错！
![image](https://github.com/user-attachments/assets/8207abd1-9869-4768-8d91-c8e393fd440b)
我集成的位置在
![image](https://github.com/user-attachments/assets/27033672-c285-4e4a-9a14-adc87dd9ae28)
其中from tools.gradcam_seg import GradCAMSegInterpreter这个就是demo演示的GradCAMSegInterpreter类。在请您分析一下，谢谢！

**Comment by holyseven** [comment]
看起来，stop_gradient被设成True了，导致无法计算gradient

**Comment by zcswdt** [comment]
> 看起来，stop_gradient被设成True了，导致无法计算gradient

如何解决这个报错呢？

**Comment by holyseven** [comment]
应该是把stop_gradient设成False，或者把without_gradient去掉。但具体的实现方式，因为涉及paddlepaddle和paddleseg的代码开发，我们这边精力有限，细节也不太了解。

**Comment by zcswdt** [comment]
谢谢，我成功了，注释掉paddle.no_grad()，保证梯度计算。还有个问题就是当输入图片长宽不是一样的时候，这里面的resize_to参数和crop_to参数该如何调整呢？比如使用paddleseg图片输入为291，281，输出的pred也是291，291。如果在图像中狗的区域是（100，100），resize_to和crop_to该如何调整呢？
![image](https://github.com/user-attachments/assets/c80f6152-ea3a-4284-8eb9-7219e45708ea)

**Comment by holyseven** [comment]
试试：
1. resize_to=291，crop_to=None；
2. 或者resize_to=291，crop_to=291

**Comment by zcswdt** [comment]
> 试试：
> 
> 1. resize_to=291，crop_to=None；
> 2. 或者resize_to=291，crop_to=291

那这样操作图像会变形么？比如我在原始图中的（100，100）的位置会随着这两个参数而改变吧？我看demo中的pixels = [(400, 200)]对应的是经过这两个参数操作以后的图像就是512*512图像中的位置。

**Comment by holyseven** [comment]
两种方案：

1. resize_to 调成和原图的短边大小就行，就不会变形。具体代码在这：https://github.com/PaddlePaddle/InterpretDL/blob/master/interpretdl/data_processor/readers.py#L44

2. 或者可以把 GradCAMSegInterpreter 里面的 images_transform_pipeline 重新写一下，interpretdl自带的可能写得有点死

**Comment by zcswdt** [comment]
> 两种方案：
> 
> 1. resize_to 调成和原图的短边大小就行，就不会变形。具体代码在这里：https://github.com/PaddlePaddle/InterpretDL/blob/master/interpretdl/data_processor/readers.py#L44
> 2. 或者可以把GradCAMSegInterpreter里面的images_transform_pipeline重新写一下，interpretdl自带的可能写得有点死

我表达的有点不清楚，原始的pixels（400，200）是在原图的位置还是 经过resize_to和crop_to后512大小图中的位置呢
？

**Comment by holyseven** [comment]
是resize和crop之后的位置

**Comment by zcswdt** [comment]
> 是resize和crop之后的位置

那这样不好计算阿，因为我输入的任何一张图片的尺寸都不一样阿，怎么样才能实现这个映射关系呢？就是分割出来的位置，印映射到这个缩放和裁减后的图像的位置呢？

**Comment by holyseven** [comment]
图片也可以不resize，按照之前讨论过的设置：

> 试试：
> 
> 1. resize_to=291，crop_to=None；
> 2. 或者resize_to=291，crop_to=291
