### ISSUE TITLE
GradcamSeg是否支持paddle2.4以上版本？

### ISSUE THREAD

**Issue by FelixYHH** [PaddlePaddle/InterpretDL#56]
![屏幕截图 2023-03-15 171819](https://user-images.githubusercontent.com/45309448/225263536-c94f9f91-5ac6-4f16-97b8-eadcaeb3af1d.png)

**Comment by holyseven** [comment]
支持呀。这个错误这，把`target`改成`loss`就能跑吧？另外L139可以注释掉。
