### ISSUE TITLE
请问这里边有没有和自然语言处理相关的

### ISSUE THREAD

**Issue by chongchongL** [PaddlePaddle/InterpretDL#58]
(optional) Briefly introduce yourself.

---

**Comment by holyseven** [comment]
这里，看是否是想找的：

NLP Explanations. There are four tutorials for NLP tutorials, using [Ernie2.0 in English](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/ernie-2.0-en-sst-2.ipynb) ([on NBViewer](https://nbviewer.org/github/PaddlePaddle/InterpretDL/blob/master/tutorials/ernie-2.0-en-sst-2.ipynb)), [Bert in English](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/bert-en-sst-2.ipynb) ([on NBViewer](https://nbviewer.org/github/PaddlePaddle/InterpretDL/blob/master/tutorials/bert-en-sst-2.ipynb)), [BiLSTM in Chinese](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/bilstm-zh-chnsenticorp.ipynb) ([on NBViewer](https://nbviewer.org/github/PaddlePaddle/InterpretDL/blob/master/tutorials/bilstm-zh-chnsenticorp.ipynb)) and [Ernie1.0 in Chinese](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/ernie-1.0-zh-chnsenticorp.ipynb) ([on NBViewer](https://nbviewer.org/github/PaddlePaddle/InterpretDL/blob/master/tutorials/ernie-1.0-zh-chnsenticorp.ipynb)) as examples. For text visualizations, NBViewer gives better and colorful rendering results.

**Comment by chongchongL** [comment]
十分感谢！还想继续请教下，如果是序列到序列的模型，是否可以使用这些解释器进行解释

**Comment by chongchongL** [comment]
是类似与机器翻译，我是做的代码生成，用的opennmt的encoder_decoder模型,主要包含多个lstm，每个生成的词汇都是encoder的一个输出，而且使用了束搜索，所以用shap和lime很难去解释，不知道有没有什么好方法

**Comment by chongchongL** [comment]
![image](https://user-images.githubusercontent.com/61173897/228526251-78653905-1896-4837-93cc-b0a706c2b914.png)
xiang像这个，编码器有多个输出

**Comment by holyseven** [comment]
嗯。这种需要怎样的解释呢？这和常见的Feature Importance的解释应该不一样吧？

像翻译这种，想要的解释是每个词的对应关系吗？比如[这篇文章](https://arxiv.org/pdf/1409.0473.pdf)里的一个例子图片：
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13829174/228539458-2df83471-c3b8-4a5b-aaeb-8cdbbd645e76.png">

**Comment by chongchongL** [comment]
嗯嗯，我本来想通过shap计算出每个输入词的贡献度，但是shap对这种多输出的模型好像不起作用
