### ISSUE TITLE
InterpretDL 使用的时候都是传预训练的模型给解释器， 是否可以直接给他已经训练好的模型呢

### ISSUE THREAD

**Issue by heimao63531** [PaddlePaddle/InterpretDL#6]

**Comment by holyseven** [comment]
Hi @heimao63531 

可以的。目前我们的实现是基于paddle1.8的静态图，以[smooth_grad](https://github.com/PaddlePaddle/InterpretDL/blob/master/interpretdl/interpreter/smooth_grad.py#L75-L81)为例：

```python
import interpretdl as it
def paddle_model(data):
    import paddle.fluid as fluid
    class_num = 1000
    model = ResNet50()
    logits = model.net(input=image_input, class_dim=class_num)
    probs = fluid.layers.softmax(logits, axis=-1)
    return probs
sg = it.SmoothGradInterpreter(paddle_model, "assets/ResNet50_pretrained")
gradients = sg.interpret(img_path, visual=True, save_path='assets/sg_test.jpg')
```
只需要在paddle_model函数中提供模型的构建，然后在SmoothGradInterpreter里给出模型参数的位置（上例是用的预训练模型`"assets/ResNet50_pretrained"`）。

预计这个月底我们将全面支持动态图，到时可以直接在paddle_model里载入训练好的参数，会更加方便。
