### ISSUE TITLE
 softmax(): argument 'x' (position 0) must be Tensor, but got list

### ISSUE THREAD

**Issue by toouki** [PaddlePaddle/InterpretDL#60]
import paddle
from PIL import Image
import interpretdl as it
from interpretdl.data_processor.readers import read_image
from paddleseg.models import MixVisionTransformer_B5
from paddleseg.models.backbones import *

url = 'https://bj.bcebos.com/paddleseg/dygraph/pretrained_models/vit_small_patch16_384_augreg.tar.gz'
paddle_model = ViT_base_patch16_384(pretrained=url, num_classes=2)

result = [n for n, v in paddle_model.named_sublayers()]
print(result)

tam = it.TAMInterpreter(paddle_model)

Path = "imgs/catdog.jpg"

Layer = 'norm1'

heatmap = tam.interpret(
        Path,
        start_layer=4,
        label=None,  # cat
        visual=True,
        save_path=None)

## ❓ Questions and Help
代码如上，不管我换什么网络换什么层显示都报这个错
泪目了，求助
Traceback (most recent call last):
  File "D:\project\InterpretDL-master\test.py", line 20, in <module>
    heatmap = tam.interpret(
  File "D:\project\InterpretDL-master\interpretdl\interpreter\transition_attention_maps.py", line 78, in interpret
    attns, _, preds = self.predict_fn(data)
  File "D:\project\InterpretDL-master\interpretdl\interpreter\transition_attention_maps.py", line 149, in predict_fn
    out = paddle.nn.functional.softmax(out, axis=1)
  File "C:\soft\anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\activation.py", line 1142, in softmax
    return _C_ops.softmax(outs_cast, axis)
ValueError: (InvalidArgument) softmax(): argument 'x' (position 0) must be Tensor, but got list (at ..\paddle\fluid\pybind\eager_utils.cc:894)

**Comment by holyseven** [comment]
目前看到两个问题：

Paddleseg的backbone，输出有两个结果，而且第一个结果是一个list，见[paddleseg源代码](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/paddleseg/models/backbones/vision_transformer.py#L259-L281)

```python
return res, x_shape
```

目前我们用的ViT实现方法都是稍微改过的，见[interpretdl源代码](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/assets/vision_transformer.py#L282-L285)

```python
return x
```

这个可以改原模型的代码，也可以改解释算法的predict_fn。


另一个问题是paddleseg的backbone只输出features，并没有做分类的classification。

如果是想做分类模型的热力图，可参考interpretdl的[examples](https://github.com/PaddlePaddle/InterpretDL/tree/master/examples)；如果是想做分割模型的热力图，可参考[这个](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb)和[这个](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/InputGrad_Segmentation.ipynb)。

**Comment by toouki** [comment]
谢谢，我放弃了

**Comment by toouki** [comment]
[https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/GradCAM_Segmentation.ipynb](url)这个示例里的target为什么没定义

**Comment by toouki** [comment]
> 目前看到两个问题：
> 
> Paddleseg的backbone，输出有两个结果，而且第一个结果是一个list，见[paddleseg源代码](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.7/paddleseg/models/backbones/vision_transformer.py#L259-L281)
> 
> ```python
> return res, x_shape
> ```
> 
> 目前我们用的ViT实现方法都是稍微改过的，见[interpretdl源代码](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/assets/vision_transformer.py#L282-L285)
> 
> ```python
> return x
> ```
> 
> 这个可以改原模型的代码，也可以改解释算法的predict_fn。
> 
> 另一个问题是paddleseg的backbone只输出features，并没有做分类的分类。
> 
> 如果是想做分类模型的热力图，可参考interpretdl的[examples](https://github.com/PaddlePaddle/InterpretDL/tree/master/examples);如果是想做分割模型的热力图，可参考这个和[这个](https://github.com/PaddlePaddle/InterpretDL/blob/master/tutorials/InputGrad_Segmentation.ipynb)。

这个GrandCAM的分割示例函数报错，这里：
                # paddle gradient computation changes since 2.4
                paddle_version=tuple(map(int, paddle.__version__.split(".")))
                if paddle_version>=(2,4,0):
                    loss.backward(retain_graph=True) #since paddle 2.4
                    gradients = paddle.grad(
                        outputs=[target], inputs=[self._feature_maps[self._target_layer_name]])[0]
outputs的target没有定义，我该怎么改
谢谢大佬了

**Comment by toouki** [comment]
ok了，改成logits 就可以正常输出了
