### ISSUE TITLE
Failed to apply gradcam on mobileNetv3-large

### ISSUE THREAD

**Issue by dawn1206** [PaddlePaddle/InterpretDL#65]
## 🐛 Bug

I attempted to apply the Grad-CAM algorithm to mobilenetv3-large but failed. Here are the error messages and version information I have. I think it may have some connection with the issue mentioned in this topic.

### To Reproduce

1. The model is from paddle.vision.models, and the only modification is the output dimentsion of last fc layer since my number of classes doesnt match the pretrained paremeter.
2. After training, the pdmodel is stored locally, and use the python code below to load the model arch and parameter, attempting to extract the feature map.

```python
import interpretdl as it
from interpretdl.data_processor.readers import read_image
from paddle.vision.models import mobilenet_v3_large
from paddle.vision.models import resnet50

import os
import paddle
paddle.device.set_device('gpu:0')

# paddle_model = resnet50(pretrained=True)
paddle_model = mobilenet_v3_large(pretrained=True, num_classes=150) 
checkpoint_path = ""
if os.path.exists(checkpoint_path):
    param_state_dict = paddle.load(os.path.join(checkpoint_path, "mobileNetv3_5_16.pdparams"))
    paddle_model.set_state_dict(param_state_dict)

gradcam = it.GradCAMInterpreter(paddle_model, device='gpu:0')
layers_name = []
for n, v in paddle_model.named_sublayers():
    layers_name.append(n)
print(layers_name)
img_path = ''
print(paddle_model)
heatmap = gradcam.interpret(
        img_path,
        'lastconv.0',
        label=None,
        visual=True,
        save_path=None)
```

### Stacktrace 

```
Traceback (most recent call last):
  File "interpretability.py", line 24, in <module>
    heatmap = gradcam.interpret(
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/interpretdl/interpreter/gradient_cam.py", line 90, in interpret
    feature_map, gradients, preds = self.predict_fn(data, label)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/interpretdl/interpreter/gradient_cam.py", line 140, in predict_fn
    out = self.model(data)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/vision/models/mobilenetv3.py", line 237, in forward
    x = self.conv(x)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 712, in forward
    out = F.conv._conv_nd(
  File "/home/xyt/.conda/envs/paddle/lib/python3.8/site-packages/paddle/nn/functional/conv.py", line 140, in _conv_nd
    pre_bias = _C_ops.conv2d(
OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR. 
  [Hint: Please search for the error code(4) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official solution and advice about CUDNN Error.] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:227)
```

## Enviroment
- paddlepaddle-gpu          2.4.2.post116        
- NVIDIA A10         CUDA Version: 11.6

- PaddlePaddle version (eg. 2.1):  2.4.2.post116 
- CPU: AMD EPYC 7713 64-Core Processor
- GPU: 11.6/8.4.1
- OS Platform (eg. Mac OS 10.14): ubuntu18.04
- Graphics card storage: 23028MiB

**Comment by dawn1206** [comment]
I modify python3.8/site-packages/interpretdl/interpreter/gradient_cam.py as the [PR](https://github.com/PaddlePaddle/InterpretDL/pull/51) does. But there still exist problems , here is the stacktrace:
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1684376367 (unix time) try "date -d @1684376367" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e900015272) received by PID 86642 (TID 0x7f20f1b880c0) from PID 86642 ***]

已放弃 (核心已转储)
```

**Comment by holyseven** [comment]
It works on my machine:

![image](https://github.com/PaddlePaddle/InterpretDL/assets/13829174/d83fbc83-a567-4c73-8ea4-0874f9588ea3)


Try something simple to see whether the gpu is working:

```
paddle_model = mobilenet_v3_large(pretrained=True, num_classes=1000) 
paddle_model(paddle.zeros((1, 3, 224, 224)).cuda())
```

**Comment by dawn1206** [comment]
> 
This code works well but I sitll get the 'paddle::pybind::ThrowExceptionToPython(std::__exception_ptr::exception_ptr)'.
Did you modify the code for Grad-CAM, or are you running the original version? 
<img width="408" alt="image" src="https://github.com/PaddlePaddle/InterpretDL/assets/74669568/39df66b6-e6cc-408b-8abb-fd14156ba04e">
<img width="469" alt="image" src="https://github.com/PaddlePaddle/InterpretDL/assets/74669568/3755d982-7aed-413a-b086-c862c604e971">
<img width="601" alt="image" src="https://github.com/PaddlePaddle/InterpretDL/assets/74669568/f5d3e717-9639-4d99-ae44-a19a32c4836b">

**Comment by holyseven** [comment]
I'm using the current version of interpretdl, with paddle2.4.2/2.3.2 both working. But I'm using cuda10.2 and V100. I will try cuda 11.6 later and see if it still works.

**Comment by holyseven** [comment]
I tested paddle2.4.2 with cuda11.6 on V100, and didn't see such issue. 

Is there other error message that can help to locate where the error happens?

**Comment by dawn1206** [comment]
I have run the code successfully, and I find the reason why cuda keeps running error is that I set the gpu device twice. I fix that problem and my code work well, thx for your reply :)

> I tested paddle2.4.2 with cuda11.6 on V100, and didn't see such issue.
> 
> Is there other error message that can help to locate where the error happens?
