### ISSUE TITLE
在语义分割中应用GradCAM时，如何对整幅图像进行热力图显示，传入的pixels大小如何确定

### ISSUE THREAD

**Issue by aidongmandexiaowowo** [PaddlePaddle/InterpretDL#66]
(optional) Briefly introduce yourself.
在语义分割中应用GradCAM时，如何对整幅图像进行热力图显示，传入的pixels大小如何确定，我修改不同的pixels数值，结果不太一样
---

**Comment by holyseven** [comment]
对应的pixels大小可以根据使用的语义分割模型来定。一般而言，图像尺寸不同，模型分割的结果也会有细微差别，体现在热力图解释上，可能区别会更大

**Comment by aidongmandexiaowowo** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        谢谢你的回复，我等着在调整一下pixel的大小。
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Li ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年9月19日 09:13
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [PaddlePaddle/InterpretDL] 在语义分割中应用GradCAM时，如何对整幅图像进行热力图显示，传入的pixels大小如何确定 (Issue #66)
        
      
    
  
  
对应的pixels大小可以根据使用的语义分割模型来定。一般而言，图像尺寸不同，模型分割的结果也会有细微差别，体现在热力图解释上，可能区别会更大
