### ISSUE TITLE
怎么拿出paddledetection中间的某一层进行可视化

### ISSUE THREAD

**Issue by guoqsGary** [PaddlePaddle/InterpretDL#67]
怎么拿出paddledetection中间的某一层进行可视化呢？

**Comment by holyseven** [comment]
目前ppdet已经集成了相关算法，可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/GradCAM_cn.md。
可以调整相关参数`--target_feature_layer_name`
