### ISSUE TITLE
wrong url

### ISSUE THREAD

**Issue by neouyghur** [PaddlePaddle/InterpretDL#68]
https://github.com/PaddlePaddle/InterpretDL/blame/ae200116fc31e4ffeff24c5d16dbfc565172ed48/interpretdl/evaluate_interpreter/perturbation.py#L28

**Comment by holyseven** [comment]
It seems correct. In page 6.

**Comment by neouyghur** [comment]
Now it is working. Maybe my mistake, but it is better to put the paper name
as well.
