### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by HansenLYX0708** [PaddlePaddle/InterpretDL#9]
使用pip直接安装报错：
`  ERROR: Could not find a version that satisfies the requirement interpretDL (from versions: none)
ERROR: No matching distribution found for interpretDL`

**Comment by holyseven** [comment]
Hi, @HansenLYX0708 

这个报错的原因可能是pip源的选择，建议使用pip默认源、清华源或百度源。

我这边没复现出这个问题，如果后续还是没安装成功，需要提供详细的环境配置情况，以便分析报错原因。
